# Generated by Django 5.0.2 on 2024-05-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article_articlehit_ipaddress_remove_video_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='ویدئوها'),
        ),
    ]
