# Generated by Django 5.0.2 on 2024-05-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_article_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vakil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='شماره پروانه')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, verbose_name='جنسیت')),
                ('date', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('lastname', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('thumbnail', models.ImageField(upload_to='images', verbose_name='تصویر وکیل')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='video',
        ),
    ]
