# Generated by Django 5.0.2 on 2024-05-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_article_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('standard', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='vakil',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویر وکیل'),
        ),
    ]
