# Generated by Django 5.0.2 on 2024-05-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_studentdata_alter_vakil_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vakil',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='شهر'),
        ),
    ]
