# Generated by Django 5.0.2 on 2024-06-05 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_riyasat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('raees', models.BooleanField(default=False)),
                ('aaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vakil')),
            ],
        ),
    ]
