# Generated by Django 5.0.2 on 2024-06-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_comision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='aaza',
        ),
        migrations.AddField(
            model_name='comision',
            name='aaza',
            field=models.ManyToManyField(to='home.vakil'),
        ),
    ]
