# Generated by Django 5.0.2 on 2024-06-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_comision_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
