# Generated by Django 5.0.2 on 2024-06-07 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_comision_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='aaza',
        ),
        migrations.AddField(
            model_name='comision',
            name='aaza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.vakil'),
        ),
    ]
