# Generated by Django 5.0.2 on 2024-06-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_comision_aaza_comision_aaza'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionVarzeshi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('raees', models.BooleanField(default=False)),
                ('aaza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aazas', to='home.vakil')),
            ],
        ),
    ]
