# Generated by Django 5.0.2 on 2024-06-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_comisionvarzeshi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comisionvarzeshi',
            name='name',
        ),
    ]
