# Generated by Django 5.0.2 on 2024-07-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_riyasat_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riyasat',
            name='role',
            field=models.CharField(max_length=50, verbose_name='نقش'),
        ),
    ]
