# Generated by Django 5.0.2 on 2024-08-17 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_riyasat_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.article')),
            ],
        ),
    ]
