# Generated by Django 5.0.2 on 2024-08-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='articleimages/'),
        ),
    ]
