# Generated by Django 5.0.2 on 2024-08-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_articleimage_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riyasat',
            name='vakil',
        ),
        migrations.AddField(
            model_name='riyasat',
            name='vakil',
            field=models.ManyToManyField(to='home.vakil'),
        ),
    ]
