# Generated by Django 5.0.2 on 2024-08-29 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_riyasat_vakil_riyasat_vakil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riyasat',
            name='vakil',
        ),
        migrations.AddField(
            model_name='riyasat',
            name='vakil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vakils', to='home.vakil', verbose_name='وکیل'),
        ),
    ]
