# Generated by Django 5.0.2 on 2024-08-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_riyasat_vakil_riyasat_vakil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riyasat',
            name='vakil',
        ),
        migrations.AddField(
            model_name='riyasat',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
