# Generated by Django 5.0.2 on 2024-10-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='تصویر مقاله'),
        ),
    ]
