# Generated by Django 5.0.2 on 2024-11-09 09:44

import django.db.models.fields.related
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='aaza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ManyToManyField, to='home.vakil'),
        ),
    ]
