# Generated by Django 4.2.16 on 2024-11-11 18:35

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='aaza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ManyToManyField, to='home.vakil'),
        ),
    ]
