# Generated by Django 5.0.2 on 2024-11-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_comision_aaza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='aaza',
        ),
        migrations.AddField(
            model_name='comision',
            name='vakils',
            field=models.ManyToManyField(blank=True, null=True, related_name='comisions', to='home.vakil'),
        ),
    ]
