# Generated by Django 4.2.16 on 2024-11-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_comision_aaza_alter_comisionvarzeshi_aaza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='aaza',
        ),
        migrations.AddField(
            model_name='comision',
            name='vakil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vakkils', to='home.vakil'),
        ),
    ]
