# Generated by Django 4.2.16 on 2024-11-15 14:41

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_comision_aaza_comision_vakil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='vakil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ManyToManyField, related_name='vakkils', to='home.vakil'),
        ),
    ]
