# Generated by Django 4.2.16 on 2024-11-15 15:21

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_comision_vakil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='vakil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.ManyToManyField, related_name='cvakils', to='home.vakil'),
        ),
    ]
