# Generated by Django 4.2.16 on 2024-11-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_comision_vakil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='vakil',
        ),
        migrations.AddField(
            model_name='comision',
            name='vakils',
            field=models.ManyToManyField(blank=True, null=True, related_name='comisions', to='home.vakil'),
        ),
    ]
